-- 01-table-demandes.sql
-- Cree la table demandes, active le controle d'acces (RLS) et pose la
-- VUE PUBLIQUE demandes_publiques.
-- Prototype d'apprentissage BKL-FOR-006 (fiche A de l'atelier AI-Shift du
-- 26/08/2026) -- executable tel quel dans le SQL Editor de Supabase,
-- PostgreSQL standard.
--
-- Forme reprise de Projects\filmographie\supabase\01-table-filmographie.sql
-- (FOR-003) et de Projects\veille-cinema\supabase\01-table-veille.sql
-- (FOR-004), avec UNE difference de fond, voulue et expliquee plus bas :
-- ici, AUCUNE policy sur la table, et une VUE pour la lecture publique.
--
-- Le drop en tete rend le script REJOUABLE : apres un essai rate, il
-- repart de zero. L'ordre compte -- la VUE d'abord, la TABLE ensuite :
-- une vue depend de sa table, et un drop de table sans cascade echouerait
-- tant que la vue existe.
--
-- 'generated by default as identity' (et non 'always') : lecon de
-- l'incident de chargement de FOR-003 -- 'always' REFUSE un id fourni de
-- l'exterieur. La function n'en fournit pas, mais la forme de la maison
-- reste la meme, et un import manuel resterait possible.
--
-- Fichier destine a une MACHINE (colle dans l'editeur SQL de Supabase) :
-- UTF-8 SANS BOM, derogation nommee du mandat rubrique 6.

drop view if exists public.demandes_publiques;
drop table if exists public.demandes;

-- ---------------------------------------------------------------------
-- LA TABLE -- les 12 champs de la fiche A, dans son ordre.
-- ---------------------------------------------------------------------
-- POURQUOI UN 'check' ET NON UN TYPE 'enum' POSTGRES : un type nomme
-- rend le script MAL REJOUABLE. Le 'drop type' depend de l'ordre (il
-- echoue tant qu'une colonne l'utilise, et il faut donc le placer apres
-- le drop de la table), et un type oublie d'un essai precedent fait
-- echouer le 'create type' du suivant. Un 'check' vit et meurt avec sa
-- table : le drop en tete suffit, et le script repart de zero a coup sur.
-- C'est le reglage qui compte a l'atelier, ou l'on rejoue.
--
-- LES SIX VALEURS de statut sont le CALQUE des six sections de la file
-- d'attente films-a-traiter.md (arbitrage AH n.4 du 23/08/2026),
-- section par section :
--
--   'proposee'     <- "Proposes (tiers -- a valider par toi)"
--                     C'EST LE DEFAUT A L'INSERT : une demande venue du
--                     formulaire est une proposition de tiers, et le
--                     critere de sortie de la fiche l'exige.
--   'a_traiter'    <- "A traiter"
--   'scholar'      <- "File Scholar (traitement SUPERVISE volet avance)"
--   'candidat'     <- "Candidats (inventaire CSV -- a valider par AH)"
--   'mise_de_cote' <- "Mis de cote"
--   'traitee'      <- "Traites"
--
-- La fiche n'en nommait que cinq ; la sixieme ('candidat') vient du
-- calque, et son nom est un reglage declare du redacteur du mandat.
--
-- BORNE : l'IA ne pose JAMAIS un statut. Le champ n'est pas dans son
-- schema de sortie ; le code insere 'proposee' et AH seul le change, a
-- la main dans Supabase.

create table public.demandes (
    id            bigint generated by default as identity primary key,
    created_at    timestamptz not null default now(),
    titre         text not null,
    realisateur   text,
    annee         integer null,
    motif         text,
    mail          text null,
    deja_analyse  boolean not null default false,
    slug_existant text null,
    qualification jsonb null,
    statut        text not null default 'proposee'
                  constraint demandes_statut_check check (statut in (
                      'proposee', 'a_traiter', 'scholar',
                      'candidat', 'mise_de_cote', 'traitee')),
    decideur      text not null default 'AH'
);

-- Index de confort : la file publique et la recette lisent d'abord par
-- date decroissante, et le controle de doublon porte sur (titre, annee).
create index demandes_created_idx on public.demandes (created_at desc);

-- ---------------------------------------------------------------------
-- CONTROLE D'ACCES -- lire ce bloc avant de s'etonner de ne rien voir.
-- ---------------------------------------------------------------------
-- La RLS est ACTIVEE et il n'y a DELIBEREMENT AUCUNE POLICY sur la
-- table -- ni lecture, ni insertion, ni mise a jour, ni suppression.
--
-- Sans policy, personne ne touche cette table par l'API : ni un
-- visiteur, ni la clef publiable (sb_publishable_...), ni personne
-- d'autre. C'est voulu : la table porte DEUX colonnes qui ne sont pas
-- publiables, 'mail' et 'motif' (l'adresse du demandeur, et un texte
-- libre ecrit par un inconnu).
--
-- L'ECRITURE vient du SERVEUR, par la clef SECRETE (sb_secret_...), qui
-- porte le role service_role et contourne la RLS de par son role. Cette
-- clef vit UNIQUEMENT dans les variables d'environnement Netlify --
-- jamais dans ce depot, jamais dans un fichier, jamais dans un chat.
--
-- LA LECTURE publique passe par la VUE ci-dessous, et par elle seule.
--
-- Consequence pratique a l'atelier : dans le Table Editor de Supabase,
-- les lignes RESTENT VISIBLES (le tableau de bord passe par une voie
-- privilegiee), mais toute lecture de la TABLE par l'API avec la clef
-- publiable rendra une liste vide. Ce n'est pas une panne : c'est le
-- controle de confidentialite du guide, geste 11.

alter table public.demandes enable row level security;

-- ---------------------------------------------------------------------
-- LA VUE PUBLIQUE -- la seule porte de lecture (arbitrage AH n.3).
-- ---------------------------------------------------------------------
-- Dix colonnes sur douze. NI 'mail' NI 'motif' : l'adresse du demandeur
-- reste privee (contrepartie loyale de l'arbitrage n.2 -- le champ est
-- stocke et inutilise), et le motif est du texte libre ecrit par un
-- inconnu, qu'on ne republie pas sans lecture humaine.
--
-- POURQUOI PAS 'with (security_invoker = true)' -- et c'est le point que
-- la recette doit prouver : une vue creee par le role 'postgres' est en
-- SECURITY DEFINER par defaut. Elle s'execute donc avec les droits de
-- son proprietaire et CONTOURNE la RLS de la table sous-jacente. C'est
-- exactement la propriete recherchee ici : la table reste close, la vue
-- est la seule porte, et elle ne montre que des colonnes publiables.
-- Poser 'security_invoker = true' ferait executer la vue avec les droits
-- de l'appelant ('anon'), qui n'a AUCUNE policy sur la table : la vue
-- rendrait alors ZERO LIGNE, et la file publique serait vide.
--
-- ATTENDU : le linter Supabase signalera un avertissement
-- "security definer view". Il est ATTENDU et il se RAPPORTE ; il ne se
-- "corrige" pas, sous peine de vider la file.
--
-- Fait verifie sur la documentation Supabase par le redacteur du mandat
-- le 23/08/2026 -- et A RE-VERIFIER EN LIGNE au geste 11 du guide : la
-- session preparatoire n'avait aucun acces a Supabase (charte regle 7).

create view public.demandes_publiques as
select id,
       created_at,
       titre,
       realisateur,
       annee,
       deja_analyse,
       slug_existant,
       qualification,
       statut,
       decideur
  from public.demandes;

-- Le role 'anon' est celui que porte la clef publiable de file.html.
-- SELECT seulement : aucun insert, aucune mise a jour, aucune
-- suppression par cette voie.
grant select on public.demandes_publiques to anon;
