-- 03-droits-vue-publique.sql
--
-- =====================================================================
-- NOTE DATEE DU 18/09/2026 -- BKL-CIN-096 (b) lot 2, posture W2.
-- Rien n'est reecrit ci-dessous (charte regle 5).
--
-- Deux phrases de ce fichier ont cesse d'etre vraies :
--   * l. 54 : "Tant que la table n'a aucune policy, la RLS filtrait deja
--     les LIGNES." La table porte desormais TROIS policies NOMINATIVES
--     (05-page-privee-w2.sql).
--   * l. 86 : "Le revoke sur la TABLE ne se defait pas : la table n'a
--     aucune policy, un droit rendu n'ouvrirait aucune ligne
--     aujourd'hui." Ce n'est plus le cas : depuis le lot 2, un droit
--     rendu a authenticated OUVRIRAIT les lignes que les policies
--     laissent passer. Le revoke de la l. 60 reste donc necessaire, et
--     il est RAPPELE en tete de 05 -- qui accorde ensuite, par COLONNE,
--     le strict minimum.
--
-- CE QUI N'A PAS CHANGE, et c'est l'essentiel : anon -- la clef
-- publiable, en clair dans file.html -- ne detient TOUJOURS rien d'autre
-- que SELECT sur la vue. Le lot 2 n'a rien accorde a anon.
-- Le revoke du SELECT d'authenticated sur la VUE (l. 49) reste lui aussi
-- entier : la page privee lit la TABLE, pas la vue -- elle a besoin de
-- motif et de mail, que la vue ne porte pas. La question posee l. 48
-- ("Si le lot 2 en a besoin, il le reposera") est donc tranchee : NON.
--
-- Etat courant : 05-page-privee-w2.sql ; mesure : controles n.12 a 18 de
-- 02-controles-demandes.sql.
-- =====================================================================
--
-- Retire a la clef PUBLIABLE (role anon) et au role authenticated tout
-- droit d'ECRITURE sur la vue publique demandes_publiques et tout droit
-- sur la table demandes. BKL-CIN-096 (b) lot 0, 16/09/2026.
--
-- !!! CE SCRIPT NE CONTIENT NI 'drop' NI 'create' : C'EST LUI, ET NON
-- !!! 01-table-demandes.sql, QUI SE JOUE SUR LA BASE EN PRODUCTION.
-- !!! 01 commence par 'drop view' puis 'drop table' : le rejouer en
-- !!! production DETRUIRAIT toutes les demandes.
--
-- !!! "Rejouable sans effet de bord" : FAUX depuis le 18/09/2026 -- CE
-- !!! SCRIPT NE SE REJOUE JAMAIS SEUL (avertissement date, fin de fichier).
--
-- ---------------------------------------------------------------------
-- POURQUOI (RISKLOG R-023 ; analyse CIN-096 (a) L2.0)
-- ---------------------------------------------------------------------
-- 1. La vue demandes_publiques est SIMPLE (une table, ni agregat ni
--    DISTINCT) : PostgreSQL la rend AUTOMATIQUEMENT MODIFIABLE -- un
--    INSERT, UPDATE ou DELETE sur la vue s'applique a la table, pourvu
--    que l'appelant detienne le privilege correspondant SUR LA VUE.
-- 2. Elle s'execute avec les droits de son PROPRIETAIRE (postgres), et
--    CONTOURNE donc la RLS de la table (voir 01, bloc de la vue).
-- 3. Supabase accorde PAR DEFAUT aux roles anon et authenticated des
--    droits d'ecriture sur les objets du schema public. 01 ne faisait
--    que 'grant select ... to anon' et ne RETIRAIT rien.
-- Consequence : quiconque detient la clef publiable -- en clair dans
-- file.html, par construction -- pouvait modifier statut, titre ou
-- decideur d'une demande PAR LA VUE. La borne "AH seul change une etape"
-- n'etait pas tenue par la base.
--
-- Mesure G-1 d'AH (16/09/2026, information_schema.role_table_grants) :
-- AVANT, anon et authenticated detenaient les sept privileges (SELECT,
-- INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER) sur la vue ET
-- sur la table. Le revoke de l'analyse L2.0 a ete joue par AH le meme
-- jour ; ce script le reprend, et retire en plus le SELECT
-- d'authenticated sur la vue (arbitrage AH, option 1, 16/09/2026).
--
-- Controle : 02-controles-demandes.sql, controle n.12.

-- ---------------------------------------------------------------------
-- 1. LA VUE : plus aucune ecriture, pour personne d'autre que postgres.
-- ---------------------------------------------------------------------
revoke insert, update, delete, truncate, references, trigger
    on public.demandes_publiques from anon, authenticated;

-- authenticated n'a aucun usage de la vue : file.html lit avec la clef
-- publiable, donc en anon. Moindre privilege (arbitrage AH, option 1).
-- Si le lot 2 (page privee, W2) en a besoin, il le reposera, a son gate.
revoke select on public.demandes_publiques from authenticated;

-- ---------------------------------------------------------------------
-- 2. LA TABLE : aucun droit, ni lecture ni ecriture, pour les deux roles.
-- ---------------------------------------------------------------------
-- Tant que la table n'a aucune policy, la RLS filtrait deja les LIGNES.
-- Le revoke ferme la COMMANDE elle-meme, et il reste vrai le jour ou une
-- policy apparait : la documentation Supabase avertit que "Adding
-- policies doesn't take those grants back".
-- qualifier.mjs n'est PAS concerne : il ecrit avec la clef SECRETE, role
-- service_role, que ce script ne touche pas.
revoke all on public.demandes from anon, authenticated;

-- ---------------------------------------------------------------------
-- 3. LA LECTURE PUBLIQUE, rejouee : la file reste lisible quoi qu'il
--    arrive plus haut.
-- ---------------------------------------------------------------------
grant select on public.demandes_publiques to anon;

-- ---------------------------------------------------------------------
-- RETOUR ARRIERE -- en commentaire, a ne jouer que sur decision d'AH.
-- ---------------------------------------------------------------------
-- Il n'existe PAS de retour arriere qui rende une ecriture a anon ou a
-- authenticated : ce serait rouvrir R-023. Les seuls gestes reversibles
-- sont les LECTURES :
--
-- (a) La file publique est vide apres ce script (file.html affiche
--     "La file n'a pas pu etre lue", ou aucune demande) : rejouer le
--     grant de lecture seul --
--
-- grant select on public.demandes_publiques to anon;
--
-- (b) Annuler l'arbitrage "option 1" (rendre a authenticated la lecture
--     des dix colonnes publiques de la vue, sans aucune ecriture) --
--
-- grant select on public.demandes_publiques to authenticated;
--
-- Le revoke sur la TABLE ne se defait pas : la table n'a aucune policy,
-- un droit rendu n'ouvrirait aucune ligne aujourd'hui, et ouvrirait
-- tout le jour ou une policy apparaitrait.
--
-- Fichier destine a une MACHINE (colle dans l'editeur SQL de Supabase) :
-- UTF-8 SANS BOM, comme ses voisins.
--
-- =====================================================================
-- !!! AVERTISSEMENT DATE DU 19/09/2026 -- CE SCRIPT NE SE REJOUE JAMAIS
-- !!! SEUL. (BKL-CIN-098 lot S : constat ; lot S bis : cet erratum.)
-- =====================================================================
-- Rien n'est reecrit (charte regle 5). L'affirmation de la l. 40 --
-- "Rejouable sans effet de bord : un 'revoke' d'un droit absent ne fait
-- rien, un 'grant' d'un droit deja detenu non plus" -- portait jusqu'au
-- 18/09/2026. Elle est FAUSSE depuis, et la l. 40 y renvoie desormais.
-- Les lignes 40-41 sont remplacees A NOMBRE EGAL, pour que les renvois
-- de la note de tete (l. 48, 49, 54, 60, 86, 89) restent justes.
--
-- CE QUI EST VRAI. Le 'revoke all on public.demandes' de la SECTION 2
-- emporte AUSSI les droits de COLONNE accordes par
-- 05-page-privee-w2.sql (section 6) et par 06-statut-publiee-pilote.sql
-- (section 6). Ce ne sont pas "des droits deja detenus" qu'un rejeu
-- rendrait a l'identique : ils tombent AVEC le 'select' de table, et
-- RIEN dans ce fichier ne les re-accorde. La note de tete du 18/09 avait
-- vu la cause (l. 11-17) SANS corriger l'affirmation.
--
-- MESURE DU 19/09/2026 vers 16h00 -- ce script a ete rejoue par meprise,
-- et voici ce que cela a coute, controles de 02-controles-demandes.sql :
--   n.12 : '0/0/0/true/true' avant  ->  '0/0/7/false/true' apres
--   n.14 : '7 / 0'           avant  ->  '0 / 0'            apres
--   n.23 : '2 | page_pilote, statut' avant -> '0 | (aucune)' apres
-- Les SEPT paires (colonne, privilege) d'authenticated sont tombees d'un
-- coup, avec son 'select' de table. LA PAGE PRIVEE est restee hors
-- service une dizaine de minutes. La surface PUBLIQUE n'a JAMAIS ete
-- affectee (HTTP 200 mesure a 16h03, en pleine panne) ; aucune donnee n'a
-- ete touchee ; RIEN ne s'est ouvert ('anon' a zero partout, 8/8 a la
-- contre-lecture hostile).
--
-- LA REPARATION, si le cas se reproduit : rejouer les 'grant' de
-- 05-page-privee-w2.sql section 6 et de 06-statut-publiee-pilote.sql
-- section 6 -- PAS ce fichier-ci. Puis relire les controles n.12, n.14
-- et n.23 de 02-controles-demandes.sql.
--
-- LA CAUSE DE LA MEPRISE, dite pour qu'elle ne se rejoue pas : des gestes
-- avaient ete NUMEROTES "1, 2, 3" a cote de fichiers nommes 01, 02, 03.
-- UN GESTE SE NOMME PAR LE NOM DE SON FICHIER, jamais par un numero nu.
--
-- AUCUNE LIGNE DE CODE DE CE FICHIER N'A CHANGE le 19/09/2026 : cet
-- erratum est en commentaires, et lui seul.
-- =====================================================================
